### ISSUE TITLE
[iOS] Doesn't work on app killed

### ISSUE THREAD

**Issue by martofeld** [rekab-app/background_locator#54] opened 2020-05-02 15:11 UTC
I downloaded the project and tested it against the provided example app. I installed it in a real iOS device and started it. Started getting a few sparse location, went to background and the project didn't show any notification but still got a few updates. As soon as you kill the app it stops.

Other info:
Had to get some work done according to the [iOS migration guide](https://flutter.dev/docs/development/ios-project-migration) to get it to work with XCode 11

Tested with
iPhone XR - 13.4.1

**Comment by mehdok** [comment] 2020-05-03 04:43
There is no need for notification on iOS.

The idea for iOS is that when app is killed and new location received the os should wake the app and execute some code and then kill the app again. After this if you open the app you should see that locations is saved. If it's not the behavior you get there might be a bug;

**Comment by martofeld** [comment] 2020-05-03 20:59
I believe it's not the behavior, I left the app killed for hours and haven't gotten any new locations, at least none that are saved via the FileManager. I've been testing mostly using the example app provided in this repo. 

Might be related but given that we are in quarantine I haven't moved much this past few days. As far as I understand this uses the significant location API from Apple.

**Comment by pkuzco** [comment] 2020-05-04 05:39
I tested both on an emulator and a real device. doesn't work on either.

I found one issue in this code:
https://github.com/rekab-app/background_locator/blob/master/ios/Classes/BackgroundLocatorPlugin.m#L93

I think you should call `startMonitoringSignificantLocationChanges` again before returning from `didFinishLaunchingWithOptions`, but I doubt this is the only issue that causes this feature not to work.

**Comment by martofeld** [comment] 2020-05-04 22:26
@pkuzco I took a look at the one you sent but doesn't seem to be working. It crashes in background when the location is updated. I've been working on trying to integrate their code in this plugin but unfortunately my iOS is not strong enough.

**Comment by martofeld** [comment] 2020-05-06 00:58
@mehdok Do you happen to have any ETAs on fixing this bug? This is the best library I've found so far for background location but this bug renders it unusable in iOS

**Comment by alexlopespereira** [comment] 2020-05-06 01:37
@mehdok I'm on a similar situation that @martofeld is. I might have to migrate to another plugin because I can not use this plugin on iOS.

**Comment by mehdok** [comment] 2020-05-06 05:01
@martofeld @alexlopespereira I'm trying my best to fix this bug a.s.a.p . In the meaning while any PR or suggestions are very welcome.

**Comment by martofeld** [comment] 2020-05-06 06:04
@mehdok that is great news!! I would love to help but unfortunately iOS is not my strong suite. I did test the plug-in that was linked earlier in the comments and it does seem to work.

**Comment by elliebike** [comment] 2020-05-08 15:27
I'll check this out! I have some experience with location tracking stuff on iOS, and I kinda really need this functionality haha

**Comment by martofeld** [comment] 2020-05-08 15:41
@elliebike @mehdok  I've been thinking a lot about this lately. As far as I can tell, the only `Location` operations you can do while the app is in background is `significantChangesMonitoring` which would mean your app gets restarted to let you know the users location (but only every 500m). 

I also read that the `CLLocationManager` can do Region Monitoring (geofencing?) and I'm not sure if that will ran while the app is killed, but if it were to run it would be a great possibility to obtain locations over smaller distance changes. It would probably require to unregister the old location and register a new `Region` based of the last location every time we get a new event.

Does any of you think that is something feasible?

**Comment by martofeld** [comment] 2020-05-11 00:57
Created #59 as a possible fix following my previous comment

**Comment by mohamnag** [comment] 2020-05-28 16:01
18 Days, a PR ready to go but no feedback :-(

**Comment by chollarasan** [comment] 2020-06-08 07:42
any update on this

**Comment by mehdok** [comment] 2020-06-09 04:08
@chollarasan There is a little problem with mentioned PR that need to be addressed before merging.

**Comment by MazEbeid** [comment] 2020-06-12 10:30
This is by far one of the most complete and useful plugins out there - but iOS background location updates are quite important - are you making progress on this front? @mehdok

**Comment by travisjayday** [comment] 2020-07-18 23:56
Any updates on this? Did the PR ever get merged to fix this? I'd love to help too because I kinda really need iOS background location updates but I'm a noob when it comes to native iOS. Does it work yet?

**Comment by mehdok** [comment] 2020-07-19 04:22
@MazEbeid @travisjayday The mentioned PR is merged and the problem should be solved in the latest version. Please Test last version and let me know if you have any problem.

**Comment by travisjayday** [comment] 2020-07-19 04:24
Thanks @mehdok, will test and report back.

**Comment by travisjayday** [comment] 2020-07-22 16:42
Yay it's working AFAICT! Even after the app is killed on iOS. Also managed to get Firebase/Firestore working in the callback, so that's awesome! Thanks for your amazing work guys :+1:

**Closed** 2020-08-17 14:53 UTC
Labels: bug

**Comment by zgosalvez** [comment] 2020-12-12 04:11
@mehdok / @travisjayday, how were you able to verify? I don't think iOS is launching the app in the background after quitting the app. But I can confirm the plugin works if the app is running/background.

**Comment by mehdok** [comment] 2020-12-12 06:18
@zgosalvez 
You can set the callback to write new locations to shared preferences, then after you kill the app and relaunch it you can see that there are some locations that received when the app was killed;

Besides this, you can see a small arrow in the status bar whenever a new location is coming;

**Comment by zgosalvez** [comment] 2020-12-12 06:25
@mehdok, I'll try that. Right now I'm using Console to see if the process is relaunched but it doesn't look like it. I can confirm tho that it subscribe to region monitoring via the logs.
```
Client ... is subscribing to notification kCLConnectionMessageRegionMonitoring
```
I set my `distanceFilter` to 1.0 in hopes of getting a log/local notification just by moving around the house. Or should I move farther? The weird thing is, I don't actually have to move when the app is running to get a log/local notification from my callback.

**Comment by mehdok** [comment] 2020-12-12 06:32
1-meter distance filter is pretty good, iOS is really accurate in this case;

> The weird thing is, I don't actually have to move when the app is running to get a log/local notification from my callback.

I'm not sure, but I think iOS will try to conserve energy at least when your app is terminated, so it is normal that you receive less location update in that case;

**Comment by jbxbergdev** [comment] 2021-10-12 11:27
@mehdok I read through this thread and am not quite sure as how to handle the app being killed by the iOS system correctly. As far as I understand, some further actions are required for iOS? Can you (or somebody else on here) please explain these steps, or even better, add them to the plugin docs?

**Comment by insoon0930** [comment] 2021-11-26 01:41
@mehdok i just found out that latest version(1.6.6) example doesn't work in IOS when app is killed... (it works in android perfectly) Reading this issue, seems like you guys solved it, but is there anything else i need to do to use it? I'm confused because it doesn't work...
