### ISSUE TITLE
FlutterJNI detached from native C++

### ISSUE THREAD

**Issue by uzenith360** [rekab-app/background_locator#113] opened 2020-07-30 12:46 UTC
Hi,

First i would like to appreciate the effort put into developing this plugin and also the patience to respond to users issues. You guys are the best!

I am building a safety app that sends location updates when the phone is shook and that needs to work even while the app is in background.

I tried to use the flutter shake sensor plugin to trigger the location update when the phone is shook but whenever the app goes into background, i get the message:

```
W/FlutterJNI(27552): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: plugins.flutter.io/sensors/accelerometer. Response ID: 0
```

i would appreciate any help 🙏

My full code:

```
import 'dart:async';
import 'dart:isolate';

import 'dart:ui';

import 'package:flutter/material.dart';

import 'package:background_locator/background_locator.dart';
import 'package:background_locator/location_dto.dart';
import 'package:background_locator/location_settings.dart';
import 'package:shake/shake.dart';
import 'package:sentry/sentry.dart';
import 'package:trackamsos/background/SOSHandler.dart';
import 'package:trackamsos/background/ensureAlwaysBackground.dart';
import 'package:trackamsos/core/helpers/getShakeThresholdGravity.dart';

class BackgroundService {
  static final BackgroundService _backgroundService =
      BackgroundService._internal();
  static const String _isolateName = "LocatorIsolate";
  static final SOSHandler sosHandler = SOSHandler();
  static final ReceivePort port = ReceivePort();
  final SentryClient sentry = SentryClient(
      dsn:
          'https://XXXXXXXXXXXXXXXXXXXXX.ingest.sentry.io/xxxx');
  static ShakeDetector shakeDetector;

  factory BackgroundService() => _backgroundService;

  Future<void> start() async {
    if (await isRunning()) {
      return;
    }
    
    if (IsolateNameServer.lookupPortByName(_isolateName) != null) {
      IsolateNameServer.removePortNameMapping(_isolateName);
    }

    IsolateNameServer.registerPortWithName(port.sendPort, _isolateName);

    await _initPlatformState();

    await ensureAlwaysBackground ();

    _startSOSListener();

    await _startLocationService();
  }

  void stop() async {
    if (!await isRunning()) {
      return;
    }

    _stopSOSListener();

    if (IsolateNameServer.lookupPortByName(_isolateName) != null) {
      IsolateNameServer.removePortNameMapping(_isolateName);
    }

    BackgroundLocator.unRegisterLocationUpdate();
  }

  Future<bool> isRunning() =>
      BackgroundLocator.isRegisterLocationUpdate() /*_isRunning*/;

  void updateShakeThreshold() => _startShakeListener();

  static Future<void> _startSOSListener() async {
    _startShakeListener();
    _startPowerButtonListener();
  }

  static void _stopSOSListener() {
    _stopShakeListener();
    _stopPowerButtonListener();
  }

  static Future<void> _startShakeListener() async {
    if (shakeDetector != null) {
      _stopShakeListener();
    }

    try {
      shakeDetector = ShakeDetector.autoStart(
          shakeThresholdGravity: getShakeThresholdGravity(),
          onPhoneShake: () => sosHandler.run());
    } catch (error, stackTrace) {
      try {
        await _backgroundService.sentry.captureException(
          exception: error,
          stackTrace: stackTrace,
        );
      } catch (error) {
        print(error);
      }
    }
  }

  static void _startPowerButtonListener() {
  }

  static void
      _stopPowerButtonListener() => null;

  static void _stopShakeListener() => shakeDetector?.stopListening();

  Future<void> _startLocationService() =>
      BackgroundLocator.registerLocationUpdate(
        locationCallback,
        //optional
        initCallback: _initCallback,
        disposeCallback: _disposeCallback,
        androidNotificationCallback: _notificationCallback,
        settings: LocationSettings(
          //Scroll down to see the different options
          notificationMsg: "Tap to Open App",
          notificationIcon: '@drawable/ic_notification',
          notificationTitle: "TrackAm SOS Activated",
          notificationIconColor: Colors.redAccent,
          notificationChannelName: 'TrackAm SOS',
          wakeLockTime: 60,
          autoStop: false,
          interval: 1,
          distanceFilter: 1000,
          accuracy: LocationAccuracy.POWERSAVE,
        ),
      ).whenComplete(_disposeCallback);

  static void _initCallback(Map<String, dynamic> args) => _startSOSListener();

  static void _disposeCallback() => _stopSOSListener();

  static void locationCallback(LocationDto locationDto) {
    final SendPort send = IsolateNameServer.lookupPortByName(_isolateName);
    send?.send(locationDto);
  }

  static void _notificationCallback() {
    print('User clicked on the notification');
  }

  Future<void> _initPlatformState() => BackgroundLocator.initialize();
  
  BackgroundService._internal();
}

```

**Comment by gpibarra** [comment] 2020-07-30 15:09
I would try not to use static variables for "sosHandler", and not static methods for the "_startSOSListener" and "_stopSOSListener" functions. So also remove "_startSOSListener" and "_stopSOSListener" from the "start" and "stop" functions. they are only in "initCallback" and "disposeCallback". I think SOS initialization should be inside the isolation process (so if "start" and "stop" executions are left out isolation). Since you are currently running it 2 times, maybe you are creating 2 instances of the soslistener method and there is some conflict.

**Comment by uzenith360** [comment] 2020-07-31 10:16
Thanks so much for this. 

I've applied the recommendations, I no longer get the error message but the shake sensor doesn't work at all.

I would create a new app and copy the github example code, then test the shake functionality to be sure the issue is not caused by another code in my app.

I would update this thread on progress.

Thanks again

**Comment by uzenith360** [comment] 2020-07-31 12:09
I just tested with the new example app and the shake sensor fired without problems.

I would refactor my code and debug where the issue is coming from.

**Comment by uzenith360** [comment] 2020-08-01 18:13
I later discovered the real issue was that the background locator callbacks need to be in the root of lib folder. I'm not sure that was pointed out anywhere in documentation.

Maybe it should be added as a note in documentation incase someone else faces this issue.

**Comment by gpibarra** [comment] 2020-08-01 20:01
I'm glad it works. I am not aware of this limitation. Maybe I was just lucky. Could you share an example where the code and another and that do not identify the location of the file?

**Comment by mehdok** [comment] 2020-08-17 13:37
It seems that the issue is solved, I'm closing the issue but feel free to open it anytime;

**Closed by mehdok** 2020-08-17 13:37 UTC
